### ISSUE TITLE
Deflate64 Support

### ISSUE THREAD

**Issue by iraizo** [zip-rs/zip#230] opened 2021-04-03 02:11 UTC
Hello, I am getting the error `UnsupportedArchive("Compression method not supported")` while trying to open a zip vile using `ZipArchive::new`, i tried printing out the object and shows me `compression_method: Unsupported(9)`, is there any fix for this?

**Comment by BenjaminRi** [comment] 2021-04-03 12:05
Hi @iraizo 
It looks like your zip file uses a compression method that is not supported by this library. What compression method does the zip file use? Is the feature flag `bzip2` active when you specify the `zip-rs` dependency in your `Cargo.toml`? Perhaps you can attach the zip file so we can reproduce and analyze the issue on our machines.

**Comment by iraizo** [comment] 2021-04-03 12:44
Hello, im not sure what kind of compression the zip uses, i have attached it [here](https://github.com/ClusterConsultant/TF2BD-Community-Lists/raw/main/All.zip)

**Comment by iraizo** [comment] 2021-04-03 13:01
Ive also tried using bzip2 which does not work

**Comment by BenjaminRi** [comment] 2021-04-03 13:02
> Hello, im not sure what kind of compression the zip uses, i have attached it [here](https://github.com/ClusterConsultant/TF2BD-Community-Lists/raw/main/All.zip)

Thanks for the zip file. It looks like your files were compressed with `Deflate64` which is a proprietary variant of `Deflate`. This library doesn't support `Deflate64` right now.

Wikipedia says:

https://en.wikipedia.org/wiki/Deflate#Deflate64/Enhanced_Deflate
> Deflate64, specified by PKWARE, is a proprietary variant of Deflate. It's fundamentally the same algorithm. What has changed is the increase in dictionary size from 32 KB to 64 KB, an extension of the distance codes to 16 bits so that they may address a range of 64 KB, and the length code, which is extended to 16 bits so that it may define lengths of three to 65,538 bytes.[4] This leads to Deflate64 having a longer compression time, and potentially a slightly higher compression ratio, than Deflate.[5] Several free and/or open source projects support Deflate64, such as 7-Zip,[6] while others, such as zlib, do not, as a result of the proprietary nature of the procedure[7] and the very modest performance increase over Deflate.[8]

This is definitely an issue, maybe we should support it since these files appear in the wild.

@iraizo Unfortunately, there is no small and easy fix for this because it's a missing feature. A developer has to extend the `zip` library to support `Deflate64` for this to work.

**Comment by BenjaminRi** [comment] 2021-04-03 13:06
> Ive also tried using bzip2 which does not work

`bzip2`-compressed zip files do work. What does not work are `.bz2` files because they are not zip files, so they have a different internal structure.

I recommend using `Deflate` (not `Deflate64`), that is always the safest bet and is widely supported.

**Comment by iraizo** [comment] 2021-04-03 13:16
Yes, the problem is that this isnt my archive, im not the one compressing it, so i guess i will use the `unzip` unix command to do so until this crate has support for it.

**Comment by Plecra** [comment] 2023-02-01 16:51
We definitely want broader format support here :) I don't think individual issues for the missing formats are useful though, so I'll close this until we start making progress with implementation support

**Closed by Plecra** 2023-02-01 16:51 UTC
Labels: enhancement, help wanted
