### ISSUE TITLE
ZipArchive::extract fails on Windows when destination path uses extended length syntax

### ISSUE THREAD

**Issue by Emerentius** [zip-rs/zip#249] opened 2021-08-06 18:13 UTC
As the title states, when I try to extract a zip archive to a destination using extended length syntax (`std::fs::canonicalize()` will always return these), then the extraction fails with the error:

`Error: Io(Os { code: 123, kind: Other, message: "Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch." })`
I googled that phrase and I believe the exact English equivalent of the (German) error message is `The filename, directory name or volume label syntax is incorrect.`

Extracting into the same directory but without using extended length syntax succeeds.

I've created a repo with a minimal example: https://github.com/Emerentius/zip_bug
The output is:

```bash
$ cargo run
   Compiling zip_bug v0.1.0 (C:\Users\MyUserName\code\zip_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target\debug\zip_bug.exe`
destination = \\?\C:\Users\MyUserName\Code\zip_bug\destination
Error: Io(Os { code: 123, kind: Other, message: "Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch." })
error: process didn't exit successfully: `target\debug\zip_bug.exe` (exit code: 1)
```

**Comment by Plecra** [comment] 2023-05-08 20:15
I can't reproduce this issue, the zip_bug program extracts successfully. I'll close this for now but **please** do reopen it if you're still experiencing the bug! It doesn't seem like any of the relevant code has been fixed since. (maybe it was a bugfix in std's create_dir_all 👀)

**Closed by Plecra** 2023-05-08 20:15 UTC
Labels: bug

**Comment by CaoKha** [comment] 2024-01-12 08:51
Hi @Plecra, I recently got this error. I noticed that there was an old Excel file .xls inside my zip file which causes the problem.
```bash
Extracting .\zips\OldExcel.zip
thread 'main' panicked at push-to-git/src/main.rs:299:58:
Can't extract zip file: Custom { kind: Other, error: Io(Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Excel file spec:
```
Type of file: Microsoft Excel 97-2003 Worksheet
‎Modified: 2/‎29/‎2016 ‏‎12:07 PM
Method: Deflate
CRC-32: 391539E0
Index: 57
```
However, the problem was resolved after I renamed the Excel file. 
Is this caused by the .NET change mentioned in #366 ?
