### ISSUE TITLE
Incorrect permissions on linux

### ISSUE THREAD

**Issue by mleduque** [zip-rs/zip#246] opened 2021-07-29 12:02 UTC
Hi,
I happen to need to uncompress zip file which apparently have some files with incorrect unix permissions set.
When Itry un uncompress these zip archives, I end up with 
```
Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```
Is there a way to skip permission setting when extracting a zip archive on linux ?

**Comment by zamazan4ik** [comment] 2022-01-22 11:12
@mleduque can you please share the affected zip file and the minimal running example? Thanks!

**Comment by mleduque** [comment] 2022-01-25 19:32
I will try but no guarantees. I just know in which context I had the problem 6 months ago.

**Comment by OwOSwordsman** [comment] 2022-06-12 18:26
I got a PermissionDenied error with [this example code](https://github.com/zip-rs/zip/blob/master/examples/extract.rs) and [this zip file](https://github.com/ICY105/Mechanization/releases/download/3.1.1/MechResourcepack_v3.1.1.zip). Here's the traceback:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:48:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/result.rs:1098:23
   4: testzip::real_main
             at ./src/main.rs:48:31
   5: testzip::main
             at ./src/main.rs:5:24
   6: core::ops::function::FnOnce::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zamazan4ik** [comment] 2022-06-12 21:42
@OwOSwordsman yes, with your example the issue is reproduced on my machine.

However, I do not know which behaviour is preffered here. E.g. your example could be fixed with commenting or advancing the part with setting unix permissions to the file/directory - you can simply comment it it the example will work fine (however, without preserving the permissions from the archive).

From one hand, you just need to fix this part with permissions. E.g. implement the 2-way algorithm. One the first step exatrct all files with default permissions, and on the second step set proper permissions to all files/directories from the archive.

From another hand, maybe we need to adjust our examples regarding the case.

What do you think?

**Comment by OwOSwordsman** [comment] 2022-06-12 22:01
Yeah commenting out the unix permissions part works fine. Thank you for bringing that to my attention because I didn't think of that. I don't need to preserve the permissions for my use case, so I'll comment it out, but I think that implementing a 2-way algorithm on the example would be good.

**Comment by Plecra** [comment] 2023-02-01 16:46
Hm, I can't reproduce using the zip file you've given here. I'll be optimistic and assume we accidentally fixed it 😉 Please open a new issue if you've got another reproducible crash.

**Closed by Plecra** 2023-02-01 16:46 UTC
Labels: bug
